Repository LefanTan/wedlab-cmput404-project, pull requests merged in 2022-03, with the labels that each got.

#61 Swagger Docs, More Post and Author tests, small fixes
  home/templates/post_list.html
  home/templates/profile.html
  home/views.py
  requirements.txt
  service/author_views.py
  service/post_views.py
  service/tests/__init__.py
  service/tests/test_author.py
  service/tests/test_post.py
  service/urls.py
  social_distribution/settings.py
  static/js/post_form.js
  static/js/profile.js
Labels: bug

#65 UPDATE: Follow Request Finished
  home/templates/followrequest_form.html
  home/templates/home.html
  home/templates/messages.html
  home/templates/requests.html
  home/urls.py
  home/views.py
  service/followrequest_views.py
  service/inbox_views.py
  service/migrations/0006_alter_author_displayname.py
  service/migrations/0007_followrequest.py
  service/migrations/0008_alter_followrequest_id.py
  service/migrations/0009_merge_0006_inboxobject_0008_alter_followrequest_id.py
  service/models.py
  service/serializers.py
  service/tests/test_followrequest.py
  service/urls.py
  static/css/followrequest_form.css
  static/css/home.css
  static/css/inbox.css
  static/css/style.css
  static/js/followrequest_form.js
  static/js/inbox_messages.js
  static/js/inbox_requests.js
Labels: Front-end, Back-end, Database

#68 UPDATE: Basic Inbox Functionality Finished
  home/templates/home.html
  home/templates/messages.html
  home/templates/post_form.html
  home/templates/requests.html
  home/urls.py
  home/views.py
  service/followrequest_views.py
  service/inbox_views.py
  service/migrations/0010_alter_author_displayname.py
  service/migrations/0011_alter_followrequest_object.py
  service/models.py
  static/css/home.css
  static/css/inbox.css
  static/js/followrequest_form.js
  static/js/inbox.js
  static/js/inbox_messages.js
Labels: Front-end, Back-end, Database

#74 UPDATE: Comment On Posts; Create Image posts; Host image on own server
  .env.example
  .gitignore
  home/templates/home.html
  home/templates/post_form.html
  home/templates/post_list.html
  home/views.py
  requirements.txt
  service/comment_views.py
  service/imagepost_views.py
  service/migrations/0001_initial.py
  service/migrations/0002_alter_post_contenttype.py
  service/migrations/0003_remove_author_uuid_remove_post_uuid_alter_author_id_and_more.py
  service/migrations/0004_alter_post_visibility.py
  service/migrations/0005_alter_post_description.py
  service/migrations/0006_alter_author_displayname.py
  service/migrations/0006_inboxobject.py
  service/migrations/0007_followrequest.py
  service/migrations/0008_alter_followrequest_id.py
  service/migrations/0009_merge_0006_inboxobject_0008_alter_followrequest_id.py
  service/migrations/0010_alter_author_displayname.py
  service/migrations/0011_alter_followrequest_object.py
  service/models.py
  service/post_views.py
  service/serializers.py
  service/urls.py
  social_distribution/settings.py
  social_distribution/storage_backend.py
  social_distribution/urls.py
  static/css/share_post.css
  static/js/home.js
Labels: Front-end, Back-end, Database

#75 UPDATE: Inbox Display of comments, posts and follow requests
  home/templates/messages.html
  home/templates/requests.html
  home/views.py
  service/migrations/0002_alter_followrequest_object.py
  service/migrations/0004_merge_20220323_0701.py
  service/models.py
  service/tests/test_followrequest.py
Labels: Front-end
